export const ERROR_CODES = {
  NO_TOKEN: "NO_TOKEN",
  TOKEN_INVALID_FORMAT: "TOKEN_INVALID_FORMAT",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  TOKEN_MALFORMED: "TOKEN_MALFORMED",
  TOKEN_CREDENTIAL_INVALID: "TOKEN_CREDENTIAL_INVALID",
  TOKEN_UNKNOWN_ERROR: "TOKEN_UNKNOWN_ERROR",
  USER_DISABLED: "USER_DISABLED",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  FORBIDDEN: "FORBIDDEN",
  DUPLICATE_SONG: "DUPLICATE_SONG",
  SONG_NOT_FOUND: "SONG_NOT_FOUND",
  SONG_UPLOAD_FAILED: "SONG_UPLOAD_FAILED",
  SEARCH_ERROR: "SEARCH_ERROR",
  PLAYLIST_NOT_FOUND: "PLAYLIST_NOT_FOUND",
  PLAYLIST_DUPLICATE: "PLAYLIST_DUPLICATE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export default ERROR_CODES;
